In [1]:
import numpy as np
from IPython.display import HTML
from bokeh.plotting import output_notebook, show
import genomes_dnj.lct_interval.series_plots as dm
import genomes_dnj.lct_interval.anal_series as an
import genomes_dnj.lct_interval.series_masks as sm
from genomes_dnj.lct_interval.bokeh_match_count_plot import snp_match_count_plot_cls as smcp
output_notebook(hide_banner=True)

<h3>Series 117_1685</h3>
<div style="width:700px">
<p>
This notebook documents the series 117_1685 and its 117 SNPs. The 1000 genomes data includes 2680
chromosome 2 samples that express none of these 117 SNPs and 1182 samples that express all of them.
Another 294 express 116 of them.  The repeated selection of this series of 117 SNPs is difficult
to explain by a purely random process.
<p>
There does appear to be a background of relatively random fragments of 117_1685.  But, most of
the samples that express more than 1 of the SNPs and less than 116 of them, express one of several
fragments of 117_1685 that are substantially overexpressed in 1000 genomes populations.  This
notebook explores several of these fragments.
</div>

In [2]:
HTML(dm.series_html(dm.di_117_1685))

<h3>All chromosome sample 117_1685 SNPs</h3>
<div style="width:700px">
<p>
This plot shows counts of the number of 117_1685 SNPs expressed by different 1000 genomes
chromosome 2 samples.  The distribution of counts is dominated by chromosome samples that
express none of the 117 SNPs and chromosome samples that express all of them.  Given the
large number of SNPs and multiple processes that have selected 117_1685, it is hard
to explain this distribution simply by chance association.
<p>
In the middle of the distribution, there are several cases where fragments of the 117
SNPs are overexpressed among the 1000 genome samples.  Generally, those fragments
can be associated with genetic processes associated with SNP series overexpressed
among the 1000 genome chromosome samples.
</div>

In [3]:
count_data = an.sa_117_1685.unique_snps_per_allele()
plt_obj = smcp(count_data)
plt = plt_obj.do_plot()
show(plt)

In [4]:
count_data

array([(0, 2680), (1, 153), (2, 15), (3, 7), (4, 1), (5, 4), (6, 2),
       (7, 1), (8, 1), (10, 2), (11, 5), (12, 1), (13, 1), (17, 3),
       (20, 1), (21, 13), (22, 3), (24, 2), (43, 22), (44, 2), (46, 1),
       (47, 1), (50, 1), (53, 1), (54, 1), (57, 1), (58, 1), (59, 11),
       (60, 28), (61, 167), (62, 53), (63, 2), (64, 1), (68, 1), (70, 3),
       (75, 1), (83, 2), (87, 2), (92, 6), (93, 1), (94, 2), (95, 14),
       (96, 87), (97, 4), (98, 1), (100, 5), (102, 5), (104, 1), (105, 6),
       (106, 70), (107, 5), (108, 6), (109, 1), (110, 1), (111, 41),
       (112, 3), (113, 9), (114, 12), (115, 55), (116, 294), (117, 1182)], 
      dtype=[('count', '<u2'), ('snps', '<u2')])

<h3>117_1685 SNPs</h3>
<div style="width:700px">
<p>
This plot shows the counts of 117_1685 SNPs for chromosome samples that meet
the criteria for being counted as expressing 117_1685.  The distribution
is heavily weighted towards all 117 SNPs or at least 116 of them.  But,
both the 41 samples that express 111 SNPs and the 70 samples that express
106 SNPs are cases where only a very large fragment of the 117 SNPs is really
expressed.  Both of these cases result from recombination events, one at
the high end of the 117_1685 series and the other at the bottom.
</div>

In [5]:
count_data = an.sa_117_1685.unique_snps_per_allele(sm.am_117_1685)
plt_obj = smcp(count_data)
plt = plt_obj.do_plot()
show(plt)

In [6]:
count_data

array([(105, 6), (106, 70), (107, 5), (108, 6), (109, 1), (110, 1),
       (111, 41), (112, 3), (113, 9), (114, 12), (115, 55), (116, 294),
       (117, 1182)], 
      dtype=[('count', '<u2'), ('snps', '<u2')])

In [7]:
aps_117, am_117 = an.sa_117_1685.snps_from_aps_value(117)
aps_116, am_116 = an.sa_117_1685.snps_from_aps_value(116)
am_117_or_116 = np.logical_or(am_117, am_116)
aps_116

array([293, 294, 293, 294, 294, 294, 294, 294, 294, 293, 294, 294, 294,
       294, 294, 294, 294, 294, 294, 294, 294, 294, 294, 294, 294, 294,
       294, 294, 294, 294, 294, 277, 294, 294, 294, 294, 294, 294, 294,
       294, 294, 294, 294, 294, 294, 294, 294, 224, 294, 294, 293, 294,
       294, 294, 275, 294, 294, 294, 294, 294, 294, 294, 294, 294, 277,
       293, 294, 294, 294, 293, 294, 294, 294, 294, 294, 293, 294, 241,
       294, 294, 293, 292, 294, 294, 294, 294, 294, 294, 294, 294, 292,
       294, 292, 294, 294, 294, 291, 294, 294, 294, 294, 293, 294, 292,
       294, 294, 294, 294, 293, 281, 294, 293, 294, 294, 293, 213, 293])

In [8]:
plt_obj = dm.superset_allele_mask(am_117_or_116, min_match=0.001)
plt_obj.do_plot()
HTML(plt_obj.get_html())

<h3>Series 9_39</h3>
<div style="width:700px">
<p>
The 111 SNPs expressed by 41 chromosome samples are the first 111 SNPs
of series 117_1685.  The series expressed by those 41 samples show that
they are descendents of the recombination event involving the South
Asian tree and series 8_267 that was selected by the appearance of the
series 9_39.
</div>

In [9]:
aps_111, am_111 = an.sa_117_1685.snps_from_aps_value(111)
aps_111

array([41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41,
       41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41,
       41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41,
       41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41,
       41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41,
       41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41,
       41, 41, 41, 41, 41, 41, 41, 41, 41,  0,  0,  0,  0,  0,  0])

In [10]:
plt_obj = dm.superset_allele_mask(am_111, min_match=0.5)
plt = plt_obj.do_plot()
show(plt)

In [11]:
HTML(plt_obj.get_html())

<h3>Series 22_73</h3>
<div style="width:700px">
<p>
The 106 SNPs expressed by 70 chromosome samples are the last 106 SNPs of the
series 117_1685.  The data for the series expressed by these 70 samples show
that they derive from a recombination event between the series 117_1685 and
the series 13_1696.  The resulting series association was selected by the
appearance of the series 22_73.
</div>

In [12]:
aps_106, am_106 = an.sa_117_1685.snps_from_aps_value(106)
aps_106

array([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 70, 70, 70, 70, 70, 70, 70,
       70, 70, 70, 70, 70, 70, 70, 70, 70, 70, 70, 70, 70, 70, 70, 70, 70,
       70, 70, 70, 70, 70, 70, 70, 70, 70, 70, 70, 70, 70, 70, 70, 70, 70,
       70, 70, 70, 70, 70, 70, 70, 70, 70, 70, 70, 70, 70, 70, 70, 70, 70,
       70, 70, 70, 70, 70, 70, 70, 70, 70,  0, 70, 70, 70, 70, 70, 70, 70,
       70, 70, 70, 70, 70, 70, 70, 70, 70, 70, 70, 70, 70, 70, 70, 70, 70,
       70, 70, 70, 70, 70, 70, 70, 70, 70, 70, 70, 70, 70, 70, 70])

In [13]:
plt_obj = dm.superset_allele_mask(am_106, min_match=0.5)
plt = plt_obj.do_plot()
show(plt)

In [14]:
HTML(plt_obj.get_html())

<h3></h3>
<div style="width:700px">
<p>
This plot shows counts of 117_1685 SNPs for chromosome samples that express 123_1561
but not 117_1685.  Six fragments were identified and explored further.  The first
appears to be the result of a simple recombination event.  The rest are more complicated
</div>

In [15]:
count_data = an.sa_117_1685.unique_snps_per_allele(sm.am_123_1561_not_117_1685)
plt_obj = smcp(count_data)
plt = plt_obj.do_plot()
show(plt)

In [16]:
count_data

array([(20, 1), (21, 13), (22, 3), (24, 2), (43, 22), (44, 1), (46, 1),
       (47, 1), (53, 1), (57, 1), (58, 1), (59, 11), (60, 28), (61, 167),
       (62, 53), (63, 2), (68, 1), (70, 2), (92, 4), (93, 1), (98, 1)], 
      dtype=[('count', '<u2'), ('snps', '<u2')])

In [17]:
aps_21, am_21 = an.sa_117_1685.snps_from_aps_value(21, sm.am_123_1561_not_117_1685)
aps_21

array([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 13, 13, 13, 13, 13, 13,
       13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13])

In [18]:
aps_43, am_43 = an.sa_117_1685.snps_from_aps_value(43, sm.am_123_1561_not_117_1685)
aps_43

array([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 22,  0,  0,  0,  0,  0,
        0,  0,  0, 22,  0,  0,  0,  0, 22,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 22,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 22, 22, 22, 22, 22,
       22, 22,  0, 22,  0,  0, 22,  0, 22, 22,  0, 22,  0, 22,  0, 22,  0,
       22,  0, 22, 22, 22,  0,  0,  0,  0,  0, 22, 22, 22, 22, 22, 22, 22,
       22,  0, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22])

In [19]:
aps_59, am_59 = an.sa_117_1685.snps_from_aps_value(59, sm.am_123_1561_not_117_1685)
aps_59

array([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 11,  3,  0,  3,  0,  0,
        0,  0,  0, 11, 11,  0,  0,  0, 11,  0,  0,  0, 11,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 11, 11, 11, 11, 11,
       11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11,
       11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11,  9,  9, 11, 11,
       11, 10, 11, 11, 11, 11, 11, 10, 11, 11, 11, 11, 11, 11, 11])

In [20]:
aps_60, am_60 = an.sa_117_1685.snps_from_aps_value(60, sm.am_123_1561_not_117_1685)
aps_60

array([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 28, 28,  0, 28,  0,  0,
        0,  0,  0, 28, 28,  0,  0,  0, 28,  0,  0,  0, 28,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 28, 28, 28, 28, 28,
       28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28,
       28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28,
       28,  1, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 27])

In [21]:
aps_61, am_61 = an.sa_117_1685.snps_from_aps_value(61, sm.am_123_1561_not_117_1685)
aps_61

array([  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0, 167, 167,
         0, 167,   0,   0,   0,   0,   0, 167, 167,   0,   0,   0, 167,
         0,   0,   0, 167,   1,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,  43,   0,   0,   0,   0,   0,   0,   0,   0, 167, 167,
       167, 167, 167, 167, 167, 167, 167, 167, 167, 167, 167, 167, 167,
       167, 167, 167, 167, 167, 167, 167, 167, 167, 167, 167, 167, 167,
       167, 167, 167, 167, 167, 167, 167, 167, 167, 167, 167, 167, 123,
       167, 167, 167, 167, 167, 167, 167, 167, 167, 167, 167, 167, 167])

In [22]:
aps_62, am_62 = an.sa_117_1685.snps_from_aps_value(62, sm.am_123_1561_not_117_1685)
aps_62

array([ 0,  3,  0,  0,  0,  0,  0,  0,  0,  0,  0, 53, 53,  0, 53,  0,  0,
        0,  0,  0, 53, 53,  0,  0,  0, 53,  0,  0,  0, 53,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0, 51,  0,  0,  0,  0,  0,  0,  0,  0, 53, 53, 53, 53, 53,
       53, 53, 53, 53, 53, 53, 53, 53, 53, 53, 53, 53, 53, 53, 53, 53, 53,
       53, 53, 53, 53, 53, 53, 53, 53, 53, 53, 53, 53, 53, 53, 53, 53, 53,
       53, 52, 53, 53, 53, 53, 53, 53, 53, 53, 53, 53, 53, 53, 53])

<h3>Series 22_35</h3>
<div style="width:700px">
<p>
The 59 SNP series expressed by 11 chromosome samples appears to be
mostly associated with a subset of the chromosome samples that express
the series 22_35
</div>

In [23]:
plt_obj = dm.superset_allele_mask(am_59, min_match=0.5)
plt = plt_obj.do_plot()
show(plt)

In [24]:
HTML(plt_obj.get_html())

<h3>Series 180_251</h3>
<div style="width:700px">
<p>
The 60, 61, and 62 SNP fragments appear to be associated with chromosome samples
that express the series 180_251
</div>

In [25]:
plt_obj = dm.superset_allele_mask(am_60, min_match=0.5)
plt = plt_obj.do_plot()
show(plt)

In [26]:
HTML(plt_obj.get_html())

In [27]:
plt_obj = dm.superset_allele_mask(am_61, min_match=0.5)
plt = plt_obj.do_plot()
show(plt)

In [28]:
HTML(plt_obj.get_html())

In [29]:
plt_obj = dm.superset_allele_mask(am_62, min_match=0.5)
plt = plt_obj.do_plot()
show(plt)

In [30]:
HTML(plt_obj.get_html())

<h3>Neither 117_1685, 123_1561, nor 62_1265</h3>
<div style="width:700px">
<p>
This plot shows the counts of 117_1685 SNPs for chromosome samples that don't express any
of the series 117_1685, 123_1561, or 62_1265.  The distribution is heavily weighted towards
none of the 117_1685 SNPs.  But one significant fragment of 96 SNPs expressed by 87 chromosome
samples was identified.
</div>

In [31]:
count_data = an.sa_117_1685.unique_snps_per_allele(sm.nam_117_1685_or_123_1561_or_62_1265)
plt_obj = smcp(count_data)
plt = plt_obj.do_plot()
show(plt)

In [32]:
count_data

array([(0, 2680), (1, 153), (2, 15), (3, 7), (4, 1), (5, 4), (6, 2),
       (7, 1), (8, 1), (10, 2), (11, 5), (12, 1), (13, 1), (17, 3),
       (44, 1), (50, 1), (54, 1), (64, 1), (70, 1), (75, 1), (83, 2),
       (87, 2), (92, 2), (94, 2), (95, 14), (96, 87), (97, 4), (100, 5),
       (102, 5), (104, 1)], 
      dtype=[('count', '<u2'), ('snps', '<u2')])

<h3>Series 4_815 and Series 5_684</h3>
<div style="width:700px">
<p>
The fragment of the first 96 117_1685 SNPs expressed by 87 chromosome samples
is associated with the recobination event between the South Asian and East
Asian trees that generated the series association between 4_815 and 5_684.
</div>

In [33]:
aps_96, am_96 = an.sa_117_1685.snps_from_aps_value(96, sm.nam_117_1685_or_123_1561_or_62_1265)
aps_96

array([87, 87, 87, 87, 87, 87, 87, 87, 87, 87, 87, 87, 87, 87, 87, 87, 87,
       87, 87, 87, 87, 87, 87, 87, 87, 87, 87, 87, 87, 87, 87, 87, 87, 87,
       87, 87, 87, 87, 87, 87, 87, 87, 87, 87, 87, 87, 87, 87, 87, 87, 87,
       87, 87, 87, 87, 87, 87, 87, 87, 87, 87, 87, 87, 87, 87, 87, 87, 87,
       87, 87, 87, 87, 87, 87, 87, 87, 87, 87, 87, 87, 87, 87, 87, 87, 87,
       87, 87, 87, 87, 87, 87, 87, 87, 87, 87, 87,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0])

In [34]:
plt_obj = dm.superset_allele_mask(am_96, min_match=0.9)
plt = plt_obj.do_plot()
show(plt)

In [35]:
HTML(plt_obj.get_html())